### ISSUE TITLE
part/*_side.png's 8x8 causes issues with Mipmaps

### ISSUE THREAD

**Issue by HanFox** [M3gaFr3ak/ExtraCells2#143]
Due to them being 8x8 they're too small for mipmapping to be at level 4. It's a bit trivial, but they should be 16x16. I doubt it'll effect the filesize of them too much ;)

**Comment by M3gaFr3ak** [comment]
@DrummerMC did you scale them down? I don't remember making 8x8 pngs ôO anyways, gonna push a fix now^^

**Comment by M3gaFr3ak** [comment]
https://github.com/M3gaFr3ak/ExtraCells2/commit/49bf943eaa6e19c9f75f65f93b09cddaacce6bc2
https://github.com/M3gaFr3ak/ExtraCells2/commit/0ffad16c300409fc3e4f4537b7ec626cc98f6bf1

fixed^^

**Comment by DrummerMC** [comment]
I don't make 8*8 textures

**Comment by M3gaFr3ak** [comment]
ok, then idk^^
