### ISSUE TITLE
Essentia stored by Thaumic Energistics shows in fluid terminal

### ISSUE THREAD

**Issue by gdude2002** [M3gaFr3ak/ExtraCells2#148]
Pretty much exactly what the title says.

![](http://i.imgur.com/7cHRny2.png)

This is quite annoying as it clogs up the terminal (which doesn't scroll). I'm not sure whose mod is causing this, so I've also [raised a ticket for Thaumic Energistics](https://github.com/Nividica/ThaumicEnergistics/issues/110).

**Comment by gdude2002** [comment]
This also occurs when putting the essentia and its fluid on its own subnetwork.

**Comment by ruifung** [comment]
Make the fluid term scroll then. XD Some form of sorting would be good too.

**Comment by gdude2002** [comment]
As seen in #149, the ExtraCells dev has added an API method to hide fluids. In https://github.com/Nividica/ThaumicEnergistics/issues/110, the Thaumic Energistics dev is planning to use it.

I love when this kind of thing happens, some mod authors are just the best. :P
