### ISSUE TITLE
API Request - Hide fluids

### ISSUE THREAD

**Issue by Nividica** [M3gaFr3ak/ExtraCells2#149]
Hello M3ga and team,
A reoccurring complaint that I get is that the essentia gas from Thaumic Energistics shows in the Fluid Terminal, and while this is expected behavior it appears to be unwanted.
I wanted to ask if there was any way possible to include a method in the EC API that would allow adding a fluid to a display blacklist. In effect all this would do is prevent the fluid terminal from displaying the fluid, and should have no other effect.
All of the essentia fluids I build come from a single class which I aptly named "GaseousEssentia". As such I was thinking a simple way to blacklist them would be for the API call to accept a class definition, and for the terminal to perform the instanceof check.

Another possible solution that has been suggested is the use of view cells, however I have not looked into view cells at all, and do not know if they would be a viable solution.

I would love to hear your thoughts and feedback on the matter.

Related to https://github.com/M3gaFr3ak/ExtraCells2/issues/148

**Comment by DrummerMC** [comment]
Will work on this

**Comment by Nividica** [comment]
Thank you very much Drummer

**Comment by DrummerMC** [comment]
I have add this.

**Comment by Nividica** [comment]
Above and beyond, thank you for including the storage option.
