### ISSUE TITLE
Fluid assembler lost recipies

### ISSUE THREAD

**Issue by akiradk** [M3gaFr3ak/ExtraCells2#152]
After a server restart (from what i can see) the assembler lost the recipies there was in there

**Comment by krakel** [comment]
It loss recipe after reconnect client!

**Comment by aik88** [comment]
Same with Forge 10.13.2.1277, appeng rv2 beta 7 and ec2 2.2.25b45

**Comment by DrummerMC** [comment]
Fixed in rv2
