### ISSUE TITLE
fluid assembler and fluid patterns...no idea how to use

### ISSUE THREAD

**Issue by mrgreaper** [M3gaFr3ak/ExtraCells2#156]
After googling for over an hour i admit defeat, how do we use the fluid assembler, 
i assumed we use the fluid patterns but i can only make blank ones of them
looked at the wiki on github and the forum no luck, found a few videos but there all out of date

**Comment by DrummerMC** [comment]
use the normal ae pattern

**Comment by GreenSooper** [comment]
This is the only comment of the same issue that I can find on the internet about this problem, and there's still no documentation on it.  Using version 2.2.73b129 and the normal patterns absolutely do not work.  The block won't even allow me to place them.  

An official documentation / wiki on this mod would alleviate a lot of frustrated users online.  The only valid Wiki I can find is on the FTB packs site, and it's not v2.
