### ISSUE TITLE
Crash at startup using ECrv2 jenkins build 68 (WAILA dependency)

### ISSUE THREAD

**Issue by ate0ate** [M3gaFr3ak/ExtraCells2#160]
I think there's an accidental dependency for Waila in the latest jenkins build. Crash at startup using forge 1286 and latest EC2 jenkins build...

http://pastebin.com/9wEqwt6g

**Comment by DrummerMC** [comment]
I will fix this later Button first you can use the build before

**Comment by DrummerMC** [comment]
Fixed

**Comment by ate0ate** [comment]
Thanks for the quick fix!
