### ISSUE TITLE
NoSuchMethodError with Applied Energistics 2

### ISSUE THREAD

**Issue by dedSea** [M3gaFr3ak/ExtraCells2#161]
Unable to launch server (running a number of mods).  Getting a NoSuchMethodError at extracells.Extracells.init(80)
Full error report:
http://pastebin.com/N2D2p7ez

**Comment by DrummerMC** [comment]
You use ae2-rv2 with extracells rv1 update ec to 2.2.x

**Comment by dedSea** [comment]
You're the best!  Thanks so much!
