### ISSUE TITLE
ME Fluid Storage Bus bug in ExtraCells-1.7.10-2.2.23b43 from SkyFactory 2.2.3 pack

### ISSUE THREAD

**Issue by sharkman** [M3gaFr3ak/ExtraCells2#166]
Pretty easy to reproduce bug.

ME Fluid Storage Bus filter seems not working at all.

Make the AE setup with 2 ME Fluid Storage Busses configured one for water and another for any other liquid.
(whole setup https://emc.sharkman.ru/ft/2015-01-31_03.26.22.png )
(1st bus https://emc.sharkman.ru/ft/2015-01-31_03.25.51.png )
(2nd bus https://emc.sharkman.ru/ft/2015-01-31_03.26.01.png )

Create any for of infinite water generator (Fluid transfer node with tons of speed and interaction upgrades from Extra Utilities ontop of infinite water source, attached to ME Fluid Interface will do).
(Fluid transfer node upgrades https://emc.sharkman.ru/ft/2015-01-31_03.25.43.png )

Place one drum from Extra Utilities ontop of the first bus and wait while it fills completely with water.

Exit this world and load it back.

Place another drum ontop of 2nd Storage Bus.
It will start filling with water for some reason.
(2nd drum filling https://emc.sharkman.ru/ft/2015-01-31_03.26.11.png )

world download: https://emc.sharkman.ru/ft/extracells_bug1.zip

**Comment by DrummerMC** [comment]
Fixed in rv2
