### ISSUE TITLE
ME Fuild Terminal not accept other than the bucket.

### ISSUE THREAD

**Issue by tsukineko45** [M3gaFr3ak/ExtraCells2#172]
ME Fuild Terminal not accept other than the bucket.
ex: Drum of ExtraUtilities, Universal Fuild Cell of ic2_ex and Portable Tank of ThermalExpantion.

**Comment by DrummerMC** [comment]
EC version???

**Comment by tsukineko45** [comment]
EC version is 2.1.36b43.

mods:
industrialcraft-2-2.2.650-experimental
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13
extrautilities-1.1.0k


I found now. Terminal can accept "Empty Cell" ( not Universal Fuild Cell).
So, Mod i use might cause.
I will continue to research by myself.

**Comment by DrummerMC** [comment]
try the newest rv2 version

in rv2 it should work
