### ISSUE TITLE
Can't format storage cells with ReactorCraft low pressure fluids

### ISSUE THREAD

**Issue by theron61** [M3gaFr3ak/ExtraCells2#176]
I am having an issue where low pressure fluids won't save in the cell workbench on fluid cells.  The specific names appear to be lowpammonia and lowpwater.  They work as fluids otherwise.

Any thing I can to do to help?

**Comment by DrummerMC** [comment]
Ec Version???

**Comment by theron61** [comment]
Sorry, 2.2.54b84.

**Comment by DrummerMC** [comment]
Try to fill the fluid in an ic2  universal cells and Put the cell in the cell workbench

**Comment by theron61** [comment]
Negative, tried IC2 universal cells, ExU drums and a few others.

**Comment by DrummerMC** [comment]
use the universal cell again with the newest ec version

**Comment by theron61** [comment]
Looks like it works.  Thanks!
