### ISSUE TITLE
Ore Dictionary Export Bus

### ISSUE THREAD

**Issue by tgstyle** [M3gaFr3ak/ExtraCells2#179]
This is the most awesome thing ever by the way. Just a pretty big issue with it.

I have a chest I am exporting *ore* in to, when the chest is full, instead of stopping the export from the ME. It will take a stack of say coal, but it has already exported all coal. It is now exporting gold. What happens is instead of stopping on the full chest. It will place gold in to the coal stack and turn the gold in to coal. It keeps all stacks at 64 regardless of the ore type it is importing. 

Hope this makes sense, I am using the latest RV2 B85 release.

**Comment by tgstyle** [comment]
Actually the chest doesn't even need to be full. It just turns any stack that is not 64 in to the stack that was already there. So it starts from the first slot, lets say slot 1 was empty, it exports fine to that slot, but slot 2 had 1 ender pearl. Since it is exporting anything you tell it to, slot 2 turns in to 64 ender pearls from whatever it was trying to export. It isn't a dupe per say, but you can turn anything in to whatever you want as long as it is in a not fully populated slot, and it is currently exporting to that slot.

**Comment by DrummerMC** [comment]
Fixed in rv2
