### ISSUE TITLE
Fluid Terminal Not Centered

### ISSUE THREAD

**Issue by gr8pefish** [M3gaFr3ak/ExtraCells2#180]
Using v2.2.49b75

It appears as if you had a slight error in the code for centering the fluid terminal gui. Just a few pixels too high, should be an easy fix (unless it is NEI that is causing the overlap). If you need more information, let me know. Screenshot where you can see that I can't type in the search bar easily:
![2015-02-28_07 22 12](https://cloud.githubusercontent.com/assets/6507574/6426485/8cf349da-bf1a-11e4-928b-f1e168950e35.png)

**Comment by YuRaNnNzZZ** [comment]
Confirmed on 2.2.55, NEI is disabled.
![2015-03-04_01 04 49](https://cloud.githubusercontent.com/assets/5104603/6473494/bd95e898-c20a-11e4-8f46-9ea4befedbe9.png)

**Comment by DrummerMC** [comment]
Fixed in rv2
