### ISSUE TITLE
 Crash on server start, maybe client too

### ISSUE THREAD

**Issue by Nick-77ab2** [M3gaFr3ak/ExtraCells2#194]
http://pastebin.com/jYMS4n94
crash above, weird one too,
Caused by: java.lang.NoSuchFieldError: FrontIcon
and is caused by your latest addition the BlockHardMEDrive

**Comment by PsionicArchon** [comment]
Experiencing the same issue. Simply loading into the client does not produce a crash however, attempting to boot my server does. 

I was unable to produce this crash in a single player world as of yet.

**Comment by DrummerMC** [comment]
I will look into it later.

**Comment by Protheus** [comment]
Have the same issue, v106 and 107 have the problem. Only on a server - client version of 106/107 works fine.

v101 works fine both server and client

**Comment by DrummerMC** [comment]
Fixed

**Comment by PsionicArchon** [comment]
Thanks, will be testing tonight.

**Comment by Nick-77ab2** [comment]
testing tonight also
