### ISSUE TITLE
Optifine with hires texturepack causes ExtraCells tanks to render content incorrectly

### ISSUE THREAD

**Issue by Banjobeni** [M3gaFr3ak/ExtraCells2#73]
ExtraCells with Optifine and custom texture pack (based on Misa):
![2014-09-24_22 26 27](https://cloud.githubusercontent.com/assets/8106744/4395657/4097cc40-442d-11e4-81a3-a4a94562630b.png)

ExtraCells without Optifine and with custom texture pack:
![2014-09-24_22 19 28](https://cloud.githubusercontent.com/assets/8106744/4395655/408e6b32-442d-11e4-8737-8fe1c21de844.png)

ExtraCells with Optifine but default textures:
![2014-09-24_22 12 00](https://cloud.githubusercontent.com/assets/8106744/4395656/4091d7a4-442d-11e4-9bcd-9a6a3c414c8d.png)

Don't know where to file the issue. But other tanks (Railcraft, Tinker's Construct, Mekanism) show fluids as expected.

(Oh, and mybe the compound tank on the right should not accept both lava and water at the same time.)

**Comment by excelcrafter** [comment]
1.7.10-Forge10.13.2.1277 + OptiFine_1.7.10_HD_U_B4 works too
